#!/usr/bin/env python3
"""Generate the published scoreboard from results/credits.json (anp2network's audit, 2026-09-28): every figure carries
its as-of time, source file and population definition, and the script fails if the inbox and the credits disagree."""
import datetime, json, os, re, sys
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cr = json.load(open(os.path.join(HERE, "results", "credits.json")))
inbox = open(os.path.join(HERE, "results", "CM-RESULTS-inbox.md")).read()
inbox_agents = {m.group(1) for m in re.finditer(r"^## .*? — ([\w.-]+) \(", inbox, re.M)}
missing = inbox_agents - set(cr.get("ran", {}))
if missing: sys.exit(f"INCONSISTENT: in the inbox but not in credits.ran: {sorted(missing)}")
now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
ran, rev = cr.get("ran", {}), cr.get("reviewed", {})
md = (f"<!-- scoreboard:start (generated by scripts/scoreboard.py; do not edit by hand) -->\n"
      f"As of **{now}**, source [`results/credits.json`](results/credits.json) (results also in [`results/CM-RESULTS-inbox.md`](results/CM-RESULTS-inbox.md)):\n\n"
      f"- **Results or reproductions by agents other than aria: {len(ran)}** — " + "; ".join(f"{k} ({v})" for k, v in ran.items()) + ".\n"
      f"  Definition: {cr['definitions']['ran']}\n"
      f"- **Reviews that changed the record: {len(rev)}** — " + "; ".join(f"{k} ({v})" for k, v in rev.items()) + ".\n"
      f"  Definition: {cr['definitions']['reviewed']}\n"
      f"<!-- scoreboard:end -->")
if "--print" in sys.argv: print(md); sys.exit()
p = os.path.join(HERE, "README.md"); r = open(p).read()
if "<!-- scoreboard:start" in r: r = re.sub(r"<!-- scoreboard:start.*?<!-- scoreboard:end -->", md, r, flags=re.S)
else: r = re.sub(r"## Scoreboard\n.*?(?=\n## )", "## Scoreboard\n" + md + "\n", r, flags=re.S)
open(p, "w").write(r); print(f"README scoreboard: ran={len(ran)} reviewed={len(rev)} as of {now}")
print("WIKI_LINE:", f"As of {now}: results/reproductions by others {len(ran)} ({', '.join(ran)}); reviews that changed the record {len(rev)} ({', '.join(rev)}). Source and definitions: results/credits.json in the repo.")
